#!/usr/bin/env python

import sys
import datetime
from slugify import slugify


try:
    if sys.argv[1] == 'post':
        date = datetime.datetime.now()
        slug = slugify(sys.argv[2])
        open('_posts/{date}-{slug}.md'.format(
            date=date.strftime("%Y-%m-%d"),
            slug=slug
        ), 'w')
    else:
        pass
except IndexError:
    print "./new post \"slug\""
